config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/tasks/new', to: 'tasks#new'
  post '/tasks', to: 'tasks#create'

  get '/tasks', to: 'tasks#index'
  get '/tasks/:id', to: 'tasks#show', as: 'task'

  get '/tasks/:id/edit', to: 'tasks#edit', as: 'task_edit'
  patch '/tasks/:id', to: 'tasks#update'

  delete '/tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # create
  def new
    @task = Task.new
  end

  def create
    task_params = params.require(:task).permit(:title, :details)
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end

  # read
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  # update
  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    task_params = params.require(:task).permit(:title, :details)
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end
  # delete
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_controller_helper.rb
module TasksControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit a task: <i><%= @task.title %></i></h1>

<div class="form-group">
  <%= form_for(@task) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control'%>
</div>
<div class="form-group">

  <%= f.label :details %>
  <%= f.text_field :details, class: 'form-control' %>
</div>
<div class='btn btn-primary'>
  <%= link_to "<< List", tasks_path %>
</div>
  <%= f.submit class: 'btn btn-success'%>
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

  <% @tasks.each do |task| %>
    <div class="alert alert-dark" role="alert">
      <div class="complete">
        <% if task.completed %>
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="defaultCheck2" disabled>
            <label class="form-check-label" for="defaultCheck2">
              <%= link_to task.title, task_path(task) %>
            </label>
          </div>
        <% else%>
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="defaultCheck1" disabled>
            <label class="form-check-label" for="defaultCheck1">
              <%= link_to task.title, task_path(task) %>
            </label>
          </div>
        <% end %>
      </div>
    </div>
  <%end%>

<div class="text-center">
  <div class='btn btn-success '>
    <%= link_to "Add a task", tasks_new_path(@task) %>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>New task</h1>

<div class="form-group">
  <%= form_for(@task) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control'%>
</div>
<div class="form-group">

  <%= f.label :details %>
  <%= f.text_field :details, class: 'form-control' %>
</div>
<div class='btn btn-primary'>
  <%= link_to "<< List", tasks_path %>
</div>
  <%= f.submit class: 'btn btn-success'%>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<div class="alert alert-secondary" role="alert">
  <%= @task.details %>
</div>

<div class="complete">
  <% if @task.completed %>
    <div class="form-check">
      <input class="form-check-input" type="checkbox" value="" id="defaultCheck2" disabled>
      <label class="form-check-label" for="defaultCheck2">
        This task is completed
      </label>
    </div>

  <% else%>
    <div class="form-check">
      <input class="form-check-input" type="checkbox" value="" id="defaultCheck1" disabled>
      <label class="form-check-label" for="defaultCheck1">
        This task is not completed
      </label>
    </div>
  <% end %>
</div>

<div class='btn btn-primary'>
  <%= link_to "<< List", tasks_path %>
</div>
<div class='btn btn-secondary'>
  <%= link_to "Edit", task_edit_path %>
</div>
<div class='btn btn-danger'>
  <%= link_to "Delete", task_path(@task.id),
        method: :delete,
        data: { confirm: "Are you sure?" } %>
</div>